------------- SQL Script to create tables -------------

------------- USERS -----------------
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'USERS' AND type = 'U') DROP TABLE USERS;
CREATE TABLE USERS(
    ID BIGINT,
    ROLE VARCHAR(50),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(50) UNIQUE ,
    USERNAME VARCHAR(50) UNIQUE ,
    PASSWORD VARCHAR(100),
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);
------------------------------------

------------- LAWS -----------------
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LAWS' AND type = 'U') DROP TABLE LAWS;
CREATE TABLE LAWS(
    ID BIGINT,
    TITLE VARCHAR(100),
    DESCRIPTION VARCHAR(500),
    CONSTRAINT PK_LAWS PRIMARY KEY (ID)
);
------------------------------------

------------- OFFICIAL -------------
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'OFFICIALS' AND type = 'U') DROP TABLE OFFICIALS;
CREATE TABLE OFFICIALS(
    ID BIGINT,
    CODE VARCHAR(100) UNIQUE,
    NAME VARCHAR(100),
    BIRTHDATE DATE,
    CONSTRAINT PK_OFFICIAL PRIMARY KEY (ID)
);
------------------------------------

------------- TICKETS --------------
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'TICKETS' AND type = 'U') DROP TABLE TICKETS;
CREATE TABLE TICKETS(
    ID BIGINT,
    SERIAL_NUMBER VARCHAR(500) UNIQUE,
    AMOUNT DECIMAL,
    TICKET_PLACE VARCHAR(200),
    PLATE_ID VARCHAR(50),
    BREAKER VARCHAR(100),
    TICKET_DATE DATETIME,
    CREATED_DATE DATETIME,
    VEHICLE_TYPE VARCHAR(100),
    OFFICIAL_ID BIGINT,
    CONSTRAINT PK_TICKETS PRIMARY KEY (ID),
    FOREIGN KEY (OFFICIAL_ID) REFERENCES OFFICIALS(ID)
);
-------------------------------------

------------- TICKET_LAW ------------
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'TICKET_LAW' AND type = 'U') DROP TABLE TICKET_LAW;
CREATE TABLE TICKET_LAW(
    LAW_ID BIGINT,
    TICKET_ID BIGINT,
    CONSTRAINT PK_TICKET_LAW PRIMARY KEY (LAW_ID, TICKET_ID),
    FOREIGN KEY (LAW_ID) REFERENCES LAWS(ID),
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID)
);
-------------------------------------

------------- INVOICE ---------------
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'INVOICES' AND type = 'U') DROP TABLE INVOICES;
CREATE TABLE INVOICES
(
    ID BIGINT,
    SERIAL_NUMBER VARCHAR(200) UNIQUE,
    INITIAL_AMOUNT DECIMAL,
    DISCOUNT DECIMAL,
    FEE DECIMAL,
    PAYED_AMOUNT DECIMAL,
    CREATED_DATE DATETIME,
    TICKET_ID BIGINT,
    CONSTRAINT PK_INVOICES PRIMARY KEY (ID),
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID)
);
-------------------------------------