CREATE SEQUENCE USERS_SEQUENCE_ID AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LAWS_SEQUENCE_ID AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OFFICIAL_SEQUENCE_ID AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TICKETS_SEQUENCE_ID AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INVOICES_SEQUENCE_ID AS BIGINT START WITH 1 INCREMENT BY 1;